import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coming Soon</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://res.cloudinary.com/sangsakawira/image/upload/v1672973762/Screen_Shot_2023-01-06_at_09.49.43_ldwffg.png" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
        <div style={{width: '100%', height: '100%', position: 'relative'}}>
          
          </div>
          <Image
            src="https://res.cloudinary.com/sangsakawira/image/upload/v1672973250/Screen_Shot_2023-01-06_at_09.47.15_tnqi2f.png"
            alt="Gawegawe Logo"
            height={300}
            width={900}
            priority
          />
        </div>
        <div className={styles.center}>
          <h1 className={inter.className} style={{fontSize:"70px"}}>Coming Soon</h1>
        </div>  
      </main>
    </>
  )
}
